modLoader="javafml"
loaderVersion="[46,)"
license="LGPL-3.0-only"
[[mods]]
  modId="torcherino"
  version="20.0.3"
  displayName="Torcherino"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/torcherino"
  logoFile="torcherino.png"
  authors="LukeGrahamLandry#6888, NinjaPhenix, sci4me, Moze_Intel"
  description="Adds blocks which speed up tile entities."
[[dependencies.torcherino]]
  modId="forge"
  mandatory=true
  versionRange="[46,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.torcherino]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20,1.21)"
  ordering="NONE"
  side="BOTH"
